<br>
# The Python Programming Language: Objects and map() \n
Example of class in Python

In [3]:
class Person:
    department = 'School of Information'
    
    def set_name(self,new_name):
        self.name=new_name
    def set_location(self,new_location):
        self.location=new_location
        

In [5]:
person =Person()
person.set_name('Avnesh Sharma')
person.set_location('Uttam Garden Colony')
print('{} lives in {} and working in {}'.format(person.name,person.location,person.department))


Avnesh Sharma lives in Uttam Garden Colony and working in School of Information


<br>
Here's an example of mapping the `min` function between two lists.

In [6]:
store1 = [10.00, 11.00, 12.34, 2.34]
store2 = [9.00, 11.10, 12.34, 2.01]
cheapest=map(min,store1,store2)

In [7]:
cheapest

In [8]:
for item in cheapest:
    print(item)

9.0
11.0
12.34
2.01


<br>
# The Python Programming Language: Lambda and List Comprehensions

<br>
Here's an example of lambda that takes in three parameters and adds the first two.

In [9]:
my_function = lambda a,b,c:a+b
my_function (12,3,3)

15

<br>
Let's iterate from 0 to 999 and return the even numbers and odd numbers.

In [12]:
mylist_even=[]
mylist_odd=[]
for i in range(0,1000):
    if(i%2==0):
        mylist_even.append(i)
    else:
        mylist_odd.append(i)
        
mylist_even
mylist_odd

<br>
Now the same thing but with list comprehension.

In [14]:
mylist_even= [i for i in range(0,1000) if i%2==0]
mylist_even


# The Python Programming Language: Numerical Python (NumPy)

In [16]:
import numpy as np

<br>
## Creating Arrays

In [19]:
my_list1=[1,2,3,4]
x=np.array(my_list1)
x

array([1, 2, 3, 4])

In [20]:
y=np.array([1,2,3,4,5])
y

array([1, 2, 3, 4, 5])

In [21]:
##Multidimensional array
m=np.array([[1,2,3,4],[56677,5,4,3]])
m

array([[    1,     2,     3,     4],
       [56677,     5,     4,     3]])

In [22]:
##Shape method to check the counts of rows and columns
m.shape

(2, 4)

In [24]:
##arrange retuns evenly spaced values within given time
m=np.arange(0,30,2)
m

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [25]:
    m=m.reshape(3,5)

In [26]:
m

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [27]:
o=np.linspace(0,4,9)
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [31]:


x='Dr. Christopher Brooks'
print(x[4:15])

Christopher


In [42]:
people =['Mr. Avnesh Sharma','Dr. Avnesh Sharma','Sh. Avnesh Sharma']

def Sample(person):
    return person.split()[0]+person.split()[-1]


list(map(Sample,people))

['Mr.Sharma', 'Dr.Sharma', 'Sh.Sharma']

<function __main__.<lambda>(person)>